POST http://localhost:5001/api/v1/user HTTP/1.1
content-type: application/json

{
   "firstName": "James",
   "lastName": "at the water cooler",
   "email": "james@james.com",
   "password": "pass123"
}

###
POST http://localhost:5001/api/v1/user HTTP/1.1
content-type: application/json

{
   "firstName": "Bill",
   "lastName": "Dauterive",
   "email": "dozer@main.com",
   "password": "password123"
}

###

POST http://localhost:5001/api/v1/user HTTP/1.1
content-type: application/json

{
   "firstName": "Mark",
   "lastName": "from the block",
   "email": "mark@makr.com",
   "password": "123pass"
}

###

GET http://localhost:5001/api/v1/user HTTP/1.1
Content-Type:  application/json

###

GET http://localhost:5001/api/v1/user/64f64937f78b8b4a9a195f47 HTTP/1.1
Content-Type: application/json

### 

DELETE http://localhost:5001/api/v1/user/64f64413f555d63b512f6900 HTTP/1.1
Content-Type: application/json

###

PUT http://localhost:5001/api/v1/user/64f64937f78b8b4a9a195f47 HTTP/1.1
Content-Type: application/json

{
   "firstName": "William",
   "lastName": "Fontaine de La Tour Dauterive"
}

###

PUT http://localhost:5001/api/v1/user/64f64937f78b8b4a9a195f47 HTTP/1.1
Content-Type: application/json

{
   "firstName": "",
   "lastName": "",
   "email": "wrong@email.com"
}